---
- name: Create quota1 namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace_quota1 }}"

- name: Create quota2 namespace
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace_quota2 }}"

- name: Apply ElasticQuota for quota1
  k8s:
    state: present
    definition:
      apiVersion: scheduling.x-k8s.io/v1alpha1
      kind: ElasticQuota
      metadata:
        name: quota1
        namespace: "{{ namespace_quota1 }}"
      spec:
        max:
          cpu: 6
        min:
          cpu: 4

- name: Apply ElasticQuota for quota2
  k8s:
    state: present
    definition:
      apiVersion: scheduling.x-k8s.io/v1alpha1
      kind: ElasticQuota
      metadata:
        name: quota2
        namespace: "{{ namespace_quota2 }}"
      spec:
        max:
          cpu: 6
        min:
          cpu: 4

- name: Deploy nginx to quota1
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx
        namespace: "{{ namespace_quota1 }}"
        labels:
          app: nginx
      spec:
        replicas: 4
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            name: nginx
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: "{{ nginx_image }}"
                resources:
                  limits:
                    cpu: 2
                  requests:
                    cpu: 2
            schedulerName: scheduler-plugins-scheduler

- name: Deploy nginx to quota2
  k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx
        namespace: "{{ namespace_quota2 }}"
        labels:
          app: nginx
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            name: nginx
            labels:
              app: nginx
          spec:
            containers:
              - name: nginx
                image: "{{ nginx_image }}"
                resources:
                  limits:
                    cpu: 2
                  requests:
                    cpu: 2
            schedulerName: scheduler-plugins-scheduler
