---

- name: Clean up logging resources
  include_tasks: "{{ playbook_dir }}/roles/ocp-cluster-logging/files/clf-cleanup.yml"
  when: clf_clean_up

- name: Deploy logging stack
  include_tasks: "{{ playbook_dir }}/roles/ocp-cluster-logging/files/loggingstack.yml"
  when: 
    - ocp_cluster_logging and not clf_clean_up
    - cluster_log_forwarder and not clf_clean_up
    