kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-pvc
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: iscsi
