---
- name: NetworkPolicy create, view, edit and delete operations
  block:
    - name: Create a namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              pod-security.kubernetes.io/audit: privileged
              pod-security.kubernetes.io/enforce: privileged
              pod-security.kubernetes.io/warn: privileged
              security.openshift.io/scc.podSecurityLabelSync: "false"
            name: test-2

    - name: Create network policy
      k8s:
        state: present
        definition:
          kind: NetworkPolicy
          apiVersion: networking.k8s.io/v1
          metadata:
            name: allow-27107 
            namespace: test-2
          spec:
            podSelector: 
              matchLabels:
                app: mongodb
            ingress:
            - from:
              - podSelector: 
                 matchLabels:
                   app: app
              ports: 
              - protocol: TCP
                port: 27017
      register: create_policy

    - name: View NetworkPolicy
      shell : oc get networkpolicy allow-27107 -n test-2
      register: get_policies

    - debug:
        msg: "Network Policies: {{ get_policies.stdout_lines }}"

    - name: Describe NetworkPolicy
      shell: oc describe networkpolicy.networking.k8s.io/allow-27107 -n test-2
      register: nw_policies_describe

    - debug:
        msg: "Network Policies: {{ nw_policies_describe.stdout_lines }}"

    - name: Edit NerworkPolicy 
      k8s:
        state: present
        definition:
          kind: NetworkPolicy
          apiVersion: networking.k8s.io/v1
          metadata:
            name: allow-27107
            namespace: test-2
          spec:
            podSelector:
              matchLabels:
                app: nginx
            ingress:
            - from:
              - podSelector:
                  matchLabels:
                    app: app1
              ports:
              - protocol: TCP
                port: 27017
      register: edit_policy

    - name: Describe NetworkPolicy
      shell: oc describe networkpolicy.networking.k8s.io/allow-27107 -n test-2
      register: nw_policies_describe

    - debug:
        msg: "Network Policies: {{ nw_policies_describe.stdout_lines }}"

    - name: Delete NetworkPolicy
      shell: oc delete networkpolicy allow-27107 -n test-2
      register: delete_policy
     
    - name: Create Service run-pod
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: test-2
            name: run-pod
            labels: 
              role: web
          spec:
            selector:
              app: web
            ports:
              - port: 80
                targetPort: 9376

    - name: Create POD run-pod
      k8s:
        state: present
        definition:
          kind: Pod
          metadata:
            namespace: test-2
            name: run-pod
            labels:
              role: web
          spec:
            containers:
              - name: run-pod
                image: "{{ nginx_image }}"
                ports:
                - containerPort: 80

    - name: wait for pods to come up
      shell: kubectl wait --all  --namespace=test-2 --for=condition=Ready pods --timeout=180s
      register: pods_status_1
  
    - debug:
        msg: "{{ pods_status_1 }}"

    - name: Create network policy allow-all
      k8s:
        state: present
        definition:
          kind: NetworkPolicy
          apiVersion: networking.k8s.io/v1
          metadata:
            name: web-allow-all
            namespace: test-2
          spec:
            podSelector:
              matchLabels:
                app: web
            ingress:
            - {}

    - name: Create NeworkPolicy deny-all
      k8s:
        state: present
        definition:
          kind: NetworkPolicy
          apiVersion: networking.k8s.io/v1
          metadata:
            name: web-deny-all
            namespace: test-2
          spec:
            podSelector:
              matchLabels:
                app: web
            ingress: []

    - name: View NetworkPolicy
      shell : oc get networkpolicy -n test-2
      register: nw_policies
 
    - debug:
        msg: "Network Policies: {{ nw_policies.stdout_lines }}"
    
    - name: Create A Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-deployment
            namespace: test-2
            labels:
              role: webserver
          spec:
            replicas: 2
            selector:
              matchLabels:
                role: webserver
            template:
              metadata:
                labels:
                  role: webserver
              spec:
                containers:
                - name: frontend
                  image: "{{ nginx_image }}"
                  ports:
                  - containerPort: 80

    - name: wait for pods to come up
      shell: kubectl wait --all  --namespace=test-2 --for=condition=Ready pods --timeout=180s
      register: pods_status_2
   
    - debug:
        msg: "{{ pods_status_2 }}"

    - name: Delete Resources
      shell: |
        oc delete pod run-pod -n test-2
        oc delete service run-pod -n test-2
        oc delete networkpolicy web-allow-all -n test-2
        oc delete networkpolicy web-deny-all -n test-2 
        oc delete deployment nginx-deployment -n test-2

    - name: Create result directory
      file:
        path: /root/result
        state: directory
        mode: '0755'
 
    - name: Create files for result
      file:
        path: "/root/result/{{ item }}"
        state: touch
      with_items:
        - success.txt
        - failed.txt

    - lineinfile:
        line: "NetworkPolicy Create/View/Update/Delete Success"
        path: /root/result/success.txt
        insertafter: EOF
      when:
        - create_policy.failed == false and get_policies.failed == false
        - edit_policy.failed == false and delete_policy.failed == false
        - pods_status_1.failed == false and pods_status_2.failed == false

    - lineinfile:
        line: "NetworkPolicy Create/View/Update/Delete Failed {{ item.error }}"
        path: /root/result/failed.txt
        insertafter: EOF
      with_items:
        - { name: '{{ create_policy }}', error: 'Policy Not Created' } 
        - { name: '{{ get_policies }}', error: 'Policy Not View' }
        - { name: '{{ edit_policy }}', error: 'Policy Not Edited' }
        - { name: '{{ delete_policy }}', error: 'Policy Not Deleted' }
        - { name: '{{ pods_status_1 }}', error: 'PODs are not running' }
        - { name: '{{ pods_status_2 }}', error: 'PODs are not running' }
      when: item.name.failed
  ignore_errors: yes

- name: Default Network Policy Validation
  block:
    - name: Generate the custom default project template
      shell: oc adm create-bootstrap-project-template -n default -o yaml
      register: project_template

    - name: Save the custom default project template
      copy: 
        content: "{{ project_template.stdout }}"
        dest: "{{ ovnkube_setup_directory }}/template.yml"

    - name: Add namespace to the template
      ansible.builtin.lineinfile:
        path: "{{ ovnkube_setup_directory }}/template.yml"
        insertafter: 'name: project-request'
        line: "  namespace: openshift-config"

    - name: Edit the custom default project template
      blockinfile:
        insertbefore: parameters
        block: "{{ lookup('file', '{{ role_path }}/files/default_policy.txt') }}"
        path: "{{ ovnkube_setup_directory }}/template.yml"

    - name: Patch the project configuration resource to include the project-request
      kubernetes.core.k8s:
        state: patched
        merge_type: merge
        definition:
          apiVersion: config.openshift.io/v1
          kind: Project
          metadata:
            name: cluster
          spec: 
            projectRequestTemplate: 
              name: project-request

    - name: Apply new custom default project template
      kubernetes.core.k8s:
        state: present
        src: "{{ ovnkube_setup_directory }}/template.yml"

    - name: Pause for 5 minutes to apply default policy
      pause:
        minutes: 5

    - name: Create the new project
      shell: oc new-project test-default-network-policy

    - name: Check if default network policy has been added to the new project
      shell: oc get networkpolicy -n test-default-network-policy
      register: network_policy
      until: '"allow-from-same-namespace" in network_policy.stdout'

    - name: Delete the project test-default-network-policy
      kubernetes.core.k8s:
        api_version: project.openshift.io/v1
        state: absent
        kind: Project
        name: test-default-network-policy
        wait: true
        wait_sleep: 30
        wait_timeout: 600

    - name: Delete the template
      kubernetes.core.k8s:
        api_version: template.openshift.io/v1
        state: absent
        kind: Template
        name: project-request
        namespace: openshift-config

    - name: Patch the project configuration resource to remove the project-request
      kubernetes.core.k8s:
        state: patched
        merge_type: merge
        definition:
          apiVersion: config.openshift.io/v1
          kind: Project
          metadata:
            name: cluster
          spec: 
            projectRequestTemplate: null

    - name: Save success result
      lineinfile:
        state: present
        line: "Default network policy has been successfully added to the new project."
        path: /root/result/success.txt
        insertafter: EOF
      when: not network_policy.failed

    - name: Save failure result
      lineinfile:
        state: present
        line: "Fail: Default network policy has not been added to the new project."
        path: /root/result/failed.txt
        insertafter: EOF
      when: network_policy.failed
  ignore_errors: yes

- name: Multitenant Validation
  block:
    - name: Create an OCP namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            labels:
              pod-security.kubernetes.io/audit: privileged
              pod-security.kubernetes.io/enforce: privileged
              pod-security.kubernetes.io/warn: privileged
              security.openshift.io/scc.podSecurityLabelSync: "false"
            name: test
        
    - name: Create network policy allow-from-openshift-ingress
      k8s:
        state: present
        definition:
          kind: NetworkPolicy
          apiVersion: networking.k8s.io/v1
          metadata:
            name: allow-from-openshift-ingress
            namespace: test
          spec:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    network.openshift.io/policy-group: ingress
            podSelector: {}
            policyTypes:
            - Ingress
      register: policy_1

    - name: Create network policy allow-from-openshift-monitoring
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-from-openshift-monitoring
            namespace: test
          spec:
            ingress:
            - from:
              - namespaceSelector:
                  matchLabels:
                    network.openshift.io/policy-group: monitoring
            podSelector: {}
            policyTypes:
            - Ingress
      register: policy_2

    - name: Create network policy allow-same-namespace
      k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: NetworkPolicy
          metadata:
            name: allow-same-namespace
            namespace: test
          spec:
            podSelector:
              ingress:
              - from:
                - podSelector: {}
      register: policy_3

    - name: Descibe NetworkPolicies
      shell: oc describe networkpolicy -n test
      register: output

    - debug:
        msg: "{{ output }}"

    - lineinfile:
        line: "Multitenant Success"
        path: /root/result/success.txt
        insertafter: EOF
      when:    
        - policy_1.failed == false
        - policy_2.failed == false
        - policy_3.failed == false

    - lineinfile:
        line: "Multitenant Faield {{ item.error }}"
        path: /root/result/failed.txt
        insertafter: EOF
      with_items:
        - { name: "{{ policy_1 }}", error: "Policy Not created" }
        - { name: "{{ policy_2 }}", error: "Policy Not created" }
        - { name: "{{ policy_3 }}", error: "Policy Not created" }
      when: item.name.failed
  ignore_errors: yes
