---
coo_operator_deploy: true
coo_enable_global_secret: false
coo_cleanup: true
enable_coo_stack: false
enable_logging_uiplugin: false
enable_distributed_tracing_uiplugin: false
enable_troubleshootingpanel_uiplugin: false
enable_monitoring_uiplugin: false
enable_perses_dashboard: false
coo_operator_namespace: "openshift-cluster-observability-operator"
coo_catalogsource_image: "quay.io/redhat-user-workloads/cluster-observabilit-tenant/cluster-observability-operator/coo-fbc-v4-20@sha256:c19e912526e49dc37fdaf24b4953dd671193ca3aa6797da60721d9ddfcd4daf0"
coo_channel: "stable"
coo_e2e_namespace: "coo-e2e"
coo_logstack_namespace: "openshift-logging"
coo_cluster_logging_channel: "stable-6.4"
coo_loki_channel: "stable-6.4"
coo_catalogsource_name: "coo"
tempo_operator_namespace: "openshift-tempo-operator"
opentelemetry_operator_namespace: "openshift-opentelemetry-operator"
distributed_tracing_qe_repo: "https://github.com/openshift/distributed-tracing-console-plugin.git"
distributed_tracing_qe_repo_branch: "main"
chainsaw_tarball: "https://github.com/kyverno/chainsaw/releases/download/v0.2.9-beta.1/chainsaw_linux_ppc64le.tar.gz"
chainsaw_path: "/usr/local/"
coo_work_dir: "/tmp/coo_logs"