---

- name: Check if CO are not in PROGRESSING state
  shell: oc get co | awk '{ print $4}' | grep -v PROGRESSING | grep True | wc -l
  register: co_progress_status
  until: co_progress_status.stdout|int == 0
  retries: 5
  delay: 30
  ignore_errors: yes
  
- name: Check if all CO are in AVAILABLE state
  shell: oc get co | awk '{ print $3}' | grep -v AVAILABLE | grep False | wc -l
  register: co_status
  until: co_status.stdout|int == 0
  retries: 5
  delay: 30
  ignore_errors: yes
  
- name: Check all nodes are in READY state
  shell: oc wait --all --for=condition=Ready nodes --timeout=60s

- name: Check network provider plugin
  shell: oc get network.config/cluster -o jsonpath='{.status.networkType}{"\n"}'
  register: network_provider

- debug:
    msg: "NetworkType is: {{ network_provider.stdout }}"
  failed_when: network_provider.rc != 0 or "OVNKubernetes" in network_provider.stdout

- name: Check if machineconfigpool in updated state 
  shell: |
    oc get machineconfigpool -n openshift-machine-config-operator --no-headers | awk '{ print $3 $4 $5 }' | grep -w  -v TrueFalseFalse  |  wc -l
  register: operand_count
  failed_when: operand_count.stdout|int != 0

- name: Take backup of the network operator
  shell: 'oc get Network.config.openshift.io cluster -o yaml > /root/cluster-openshift-sdn.yaml'

- name: Set the migration field on the CNO to OVNkubernetes for first
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operator.openshift.io/v1
      kind: Network
      metadata:
        name: cluster
      spec:
        migration:
          networkType: OVNKubernetes

- name: Check patch being applied - if nodes getting into ' SchedulingDisabled\|NotReady' state
  shell: |
     oc get nodes --no-headers | grep -w 'SchedulingDisabled\|NotReady' | wc -l
  register: operand_count
  until: operand_count.stdout|int > 0
  retries: 10
  delay: 30

- name: Check all nodes are in READY state
  shell: |
     oc get nodes --no-headers | grep -w 'SchedulingDisabled\|NotReady' | wc -l
  register: operand_count
  until: operand_count.stdout|int == 0
  retries: 10
  delay: 120

- name: Check if machineconfigpool in updated state 
  shell: |
    sleep 20s
    oc get machineconfigpool -n openshift-machine-config-operator --no-headers | awk '{ print $3 $4 $5 }' | grep -w  -v TrueFalseFalse  |  wc -l
  register: operand_count
  until: operand_count.stdout|int == 0
  retries: 8
  delay: 120

- name: Check if all nodes are in READY state
  shell: |
     oc get nodes --no-headers | grep -w -v 'Ready' | wc -l
  register: operand_count
  until: operand_count.stdout|int == 0
  retries: 10
  delay: 30
 
- name: Check if all machine config pods are in RUNNING state
  shell: oc get pod -n openshift-machine-config-operator | awk '{ print $3}' | grep -v STATUS | grep -v Running | wc -l
  register: mc_pods
  until: mc_pods.stdout|int == 0
  retries: 6
  delay: 120

- debug:
    msg: "Some machine config pods are not in good state"
  when: mc_pods.stdout|int != 0 

- name: Configure the OVNKubernetes cluster network provider to start migration 
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: Network
      metadata:
        name: cluster
      spec:
        networkType: OVNKubernetes

- name: Wait until the Multus daemon set pods restart
  shell: |
     oc -n openshift-multus rollout status daemonset/multus
  register: pod_restart_status
  until: pod_restart_status.stdout is search("successfully rolled out")
  retries: 5
  delay: 20

- name: Register ocp nodes hostname
  shell: oc get nodes  -o jsonpath='{.items[*].status.addresses[?(@.type=="Hostname")].address}'
  register: nodes

- name: Reboot nodes to apply changes
  shell: |
    for hostname in {{ nodes.stdout }}; do
      ssh -o StrictHostKeyChecking=no core@${hostname} sudo shutdown -r -t 3
      sleep 2m
      export nodestatus=$(oc get nodes | grep ${hostname} | grep -w Ready | wc -l)
      while [[ ${nodestatus} -ne 1 ]]
      do
        sleep 20s
        nodestatus=$(oc get nodes | grep ${hostname} | grep -w Ready | wc -l)
      done
    done
  args:
    executable: /bin/bash

- name: Check all nodes are in READY state
  shell: oc wait --all --for=condition=Ready nodes --timeout=60s

- name: Check if CO are not in PROGRESSING state
  shell: oc get co  | awk '{ print $4}' | grep -v PROGRESSING | grep True | wc -l
  register: co_progress_status
  until: co_progress_status.stdout|int == 0
  retries: 6
  delay: 120
  ignore_errors: yes

- name: Check if all CO are in AVAILABLE state
  shell: oc get co  | awk '{ print $3}' | grep -v AVAILABLE | grep False | wc -l
  register: co_status
  until: co_status.stdout|int == 0
  retries: 6
  delay: 60
  ignore_errors: yes

- name: Fail when CO are not in good status 
  fail:
    msg: "Cluster operators are not in good status after migration"
  when: 0 < co_progress_status.stdout|int or  0 < co_status.stdout|int

- name: Waiting for the PODS to start
  shell: |
     oc get pods --all-namespaces | grep -w -v 'Running\|Completed' | wc -l
  register: operand_count
  until: operand_count.stdout|int == 1
  retries: 5
  delay: 30
 
- name: Check network provider plugin
  shell: oc get network.config/cluster -o jsonpath='{.status.networkType}{"\n"}'
  register: network_provider

- debug:
    msg: " NetworkType : {{ network_provider.stdout }}" 
  failed_when: network_provider.rc != 0 or "OVNKubernetes" not in network_provider.stdout
   
- name: Remove the migration configuration from the CNO configuration object
  shell: |
    oc patch Network.operator.openshift.io cluster --type='merge' --patch '{ "spec": { "migration": null } }'

- name: Remove custom configuration for the OpenShift SDN network provider
  shell: |
    oc patch Network.operator.openshift.io cluster --type='merge' --patch '{ "spec": { "defaultNetwork": { "openshiftSDNConfig": null } } }'

- name: Delete the openshift sdn namespace
  shell: 'oc delete namespace openshift-sdn'

