---

- name: Invoke the role check-cluster-health to check cluster status
  include_role:
    name: check-cluster-health

- name: Create a coo logs directory
  ansible.builtin.file:
    path: "{{ coo_work_dir }}"
    state: directory
    mode: '0755'

- name: Deploy COO stack
  block:
    - name: Create a target namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ coo_e2e_namespace }}"

    - name: Create MonitoringStack
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.rhobs/v1alpha1
          kind: MonitoringStack
          metadata:
            labels:
              mso: example
            name: multi-ns
            namespace: "{{ coo_e2e_namespace }}"
          spec:
            alertmanagerConfig:
              disabled: false
            logLevel: info
            namespaceSelector:
              matchLabels:
                monitoring.rhobs/stack: multi-ns
            prometheusConfig:
              replicas: 2
            resourceSelector:
               matchLabels:
                app: demo
                monitoring.rhobs/stack: multi-ns
            resources: {}
            retention: 120h

    - name: Create ThanosQuerier
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: monitoring.rhobs/v1alpha1
          kind: ThanosQuerier
          metadata:
            name: example-thanos
            namespace: "{{ coo_e2e_namespace }}"
          spec:
            namespaceSelector:
              matchNames:
                - "{{ coo_e2e_namespace }}"
            selector:
              matchLabels:
                mso: example

    - name: Verify ThanosQuerier and MonitoringStack pods are running
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ coo_e2e_namespace }}"
      register: mon_pods_info
      until: mon_pods_info.resources | selectattr('status.phase','equalto','Running') | list | length >= 5
      retries: 10
      delay: 30

  when: enable_coo_stack

- name: Deploy logging UIPlugin
  block:
    - name: Deploy cluster logging operator and loki operator and lokistack
      include_role:
        name: ocp-cluster-logging
      vars:
        ocp_cluster_logging: true
        cluster_log_forwarder: true
        clf_clean_up: false
        cluster_logging_channel: "{{ coo_cluster_logging_channel}}"
        loki_channel: "{{ coo_loki_channel }}"

    - name: Get lokistack name
      k8s_info:
        api_version: loki.grafana.com/v1
        kind: LokiStack
        namespace: openshift-logging
      register: lokistack_name

    - name: Enable UIPlugin
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: observability.openshift.io/v1alpha1
          kind: UIPlugin
          metadata:
            name: logging
          spec:
            logging:
              logsLimit: 6
              lokiStack:
                name: "{{ lokistack_name.resources[0].metadata.name }}"
              timeout: 6m
            type: Logging

    - name: Verify logging UIPlugin
      shell: oc get pods -n "{{ coo_operator_namespace }}" --no-headers | grep logging | grep "Running\|Completed" | wc -l
      register: logging_pods
      until: logging_pods.stdout|int == 1 and logging_pods.stderr == ""
      retries: 10
      delay: 30
  when: enable_logging_uiplugin

- name: Check and install tempo and opentelemetry operators  
  block:
    - name: Check if Tempo Operator exists 
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: openshift-tempo-operator
      register: tempo_csv
    
    - name: Check if OpenTelemetry Operator exists
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: openshift-opentelemetry-operator
      register: opentelemetry_csv

    - name: Install tempo operator
      block:
        - name: Create a target namespace for tempo operator
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: "{{ tempo_operator_namespace }}"
                labels:
                  openshift.io/cluster-monitoring: "true"
        
        - name: Create a OperatorGroup for tempo operator
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: operators.coreos.com/v1
              kind: OperatorGroup
              metadata:
                name: "{{ tempo_operator_namespace }}"
                namespace: "{{ tempo_operator_namespace }}"

        - name: Create a subscription for tempo operator
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: "tempo-product"
                namespace: "{{ tempo_operator_namespace }}"
              spec:
                channel: "{{ coo_channel }}"
                installPlanApproval: Automatic
                name: "tempo-product"
                source: "redhat-operators"
                sourceNamespace: openshift-marketplace
        
        - name: Verfiy tempo operator installation
          shell: oc get pods -n "{{ tempo_operator_namespace }}" --no-headers | grep -v "Running\|Completed" | wc -l
          register: tempo_pods
          until: tempo_pods.stdout|int == 0 and tempo_pods.stderr == ""
          retries: 10
          delay: 30
      when: tempo_csv.resources | selectattr('metadata.name', 'search', 'tempo') | list | length == 0

    - name: Install opentelemetry operator
      block:
        - name: Create a target namespace for opentelemetry operator
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: "{{ opentelemetry_operator_namespace }}"
                labels:
                  openshift.io/cluster-monitoring: "true"
        
        - name: Create a OperatorGroup for tempo and opentelemetry operator
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: operators.coreos.com/v1
              kind: OperatorGroup
              metadata:
                name: "{{ opentelemetry_operator_namespace }}"
                namespace: "{{ opentelemetry_operator_namespace }}"

        - name: Create a subscription for opentelemetry operator
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: operators.coreos.com/v1alpha1
              kind: Subscription
              metadata:
                name: "opentelemetry-product"
                namespace: "{{ opentelemetry_operator_namespace }}"
              spec:
                channel: "{{ coo_channel }}"
                installPlanApproval: Automatic
                name: "opentelemetry-product"
                source: "redhat-operators"
                sourceNamespace: openshift-marketplace

        - name: Verfiy opentelemetry operator installation
          shell: oc get pods -n "{{ opentelemetry_operator_namespace }}" --no-headers | grep -v "Running\|Completed" | wc -l
          register: opentelemetry_pods
          until: opentelemetry_pods.stdout|int == 0 and opentelemetry_pods.stderr == ""
          retries: 10
          delay: 30
      when: opentelemetry_csv.resources | selectattr('metadata.name', 'search', 'opentelemetry') | list | length == 0
  when: enable_distributed_tracing_uiplugin or enable_troubleshootingpanel_uiplugin

- name: Deploy Distributed Tracing Console UI plugin
  block:
    - name: Create the Tracing UIPlugin CR.
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: observability.openshift.io/v1alpha1
          kind: UIPlugin
          metadata:
            name: distributed-tracing
            namespace: "{{ coo_operator_namespace }}"
          spec:
            type: DistributedTracing

    - name: Verify Tracing UI plugin
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ coo_operator_namespace }}"
      register: tracing_pods_info
      until: tracing_pods_info.resources | selectattr('metadata.name', 'search', 'distributed-tracing-') | selectattr('status.phase', 'equalto', 'Running') | list | length == 1
      retries: 10
      delay: 30

    - name: Clone Distributed Tracing QE repo
      git:
        repo: "{{ distributed_tracing_qe_repo }}"
        dest: "{{ coo_work_dir }}/distributed-tracing-console-plugin"
        version: "{{ distributed_tracing_qe_repo_branch }}"

    - name: Download and untar chainsaw
      unarchive:
        src: "{{ chainsaw_tarball }}"
        dest: "{{ chainsaw_path }}"
        remote_src: yes

    - name: Run Distributed Tracing testcases
      shell: "{{ chainsaw_path }}/chainsaw test --skip-delete {{ coo_work_dir }}/distributed-tracing-console-plugin/tests/fixtures/chainsaw-tests"
      register: tracing_tests
      async: 300
      poll: 30
      ignore_errors: true

    - name: Save the tracing tests in a file
      copy:
        content: "{{ tracing_tests.stdout }}"
        dest: "{{ coo_work_dir }}/tracing_tests_output.txt"
  when: enable_distributed_tracing_uiplugin 


- name: Deploy Troubleshooting Panel UI plugin
  block:
    - name: Create a Deployment to create Test Data
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion:  apps/v1
          kind: Deployment
          metadata:
            name: bad-deployment
            namespace: default
          spec:
            selector:
              matchLabels:
                app: bad-deployment
            template:
              metadata:
                labels:
                  app: bad-deployment
              spec:
                containers:
                - name: bad-deployment
                  image: quay.io/openshift-logging/vector:5.8

    - name: Create TroubleShooting-Panel UIPlugin CR.
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: observability.openshift.io/v1alpha1
          kind: UIPlugin
          metadata:
            name: troubleshooting-panel
          spec:
            troubleshootingPanel:
              timeout: 5m
            type: TroubleshootingPanel
 
    - name: Verify Korrel8r pod is in Running state
      k8s_info:
        kind: Pod
        namespace: "{{ coo_operator_namespace }}"
      register: korrel8r_pods
      until: >
        (
          korrel8r_pods.resources
          | selectattr('metadata.name', 'search', 'korrel8r')
          | selectattr('status.phase', 'equalto', 'Running')
          | list
          | length
        ) == 1
      retries: 10
      delay: 30

    - name: Verify troubleshooting-panel pod is in Running state
      k8s_info:
        kind: Pod
        namespace: "{{ coo_operator_namespace }}"
      register: troubleshooting_pods
      until: >
        (
          troubleshooting_pods.resources
          | selectattr('metadata.name', 'search', 'troubleshooting-panel')
          | selectattr('status.phase', 'equalto', 'Running')
          | list
          | length
        ) == 1
      retries: 10
      delay: 30
  when: enable_troubleshootingpanel_uiplugin

- name: Deploy Incidents plugin
  block:
    - name: Enable Monitoring plugin
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: observability.openshift.io/v1alpha1
          kind: UIPlugin
          metadata:
            name: monitoring
          spec:
            type: Monitoring
            monitoring:
              incidents:
                enabled: true

    - name: Verify Monitoring UIPlugin pod via label
      k8s_info:
        kind: Pod
        namespace: "{{ coo_operator_namespace }}"
      register: monitoring_pods_info
      until: >
        (
          monitoring_pods_info.resources
          | selectattr('metadata.name', 'search', 'health-analyzer')
          | selectattr('status.phase', 'equalto', 'Running')
          | list
          | length
        ) == 1
      retries: 10
      delay: 30

    - name: Check metrics are exposed
      shell: oc exec -n openshift-monitoring -it prometheus-k8s-0 -- curl -s "http://localhost:9090/api/v1/query?query=cluster:health:components"
      register: prometheus_metrics

    - name: Display prometheus metrics
      debug:
        msg: "{{ prometheus_metrics.stdout_lines }}"
  when: enable_monitoring_uiplugin

- name: Deploy Perses Config
  block:
    - name: Clone Perses Config
      ansible.builtin.git:
        repo: "https://github.com/perses/perses-operator.git"
        dest: "{{ coo_work_dir }}/perses-operator"
        force: true

    - name: Change the namespace in Perses config files
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^(\s*)namespace:.*'
        replace: '\1namespace: "{{ coo_operator_namespace }}"'
      loop:
        - "{{ coo_work_dir }}/perses-operator/config/samples/openshift/openshift-cluster-sample-dashboard.yaml"
        - "{{ coo_work_dir }}/perses-operator/config/samples/openshift/thanos-querier-datasource.yaml"

    - name: Create Perses Dashboard and Datasource
      k8s:
        state: present
        kubeconfig: "{{ coo_e2e_env.KUBECONFIG }}"
        src: "{{ item }}"
      loop:
        - "{{ coo_work_dir }}/perses-operator/config/samples/openshift/openshift-cluster-sample-dashboard.yaml"
        - "{{ coo_work_dir }}/perses-operator/config/samples/openshift/thanos-querier-datasource.yaml"
      register: perses_config
       
    - name: Fail if any failed
      ansible.builtin.fail:
        msg: "Some resources failed"
      when: |
        perses_config.results
        | selectattr('failed', 'defined')
        | selectattr('failed')
        | list
        | length > 0    

    - name: Verify Monitoring UIPlugin exists
      k8s_info:
        kind: UIPlugin
        name: monitoring
        api_version: observability.openshift.io/v1alpha1
      register: monitoring_uiplugin

    - name: Patch the Monitoring UIPlugin to enable Perses
      kubernetes.core.k8s:
        state: present
        api_version: observability.openshift.io/v1alpha1
        kind: UIPlugin
        name: monitoring
        merge_type: merge
        definition:
          spec:
            monitoring:
              perses:
                enabled: true
      when: monitoring_uiplugin.resources | selectattr('metadata.name', 'search', 'monitoring') | length > 0
    
    - name: Enable Perses
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: observability.openshift.io/v1alpha1
          kind: UIPlugin
          metadata:
            name: monitoring
          spec:
            type: Monitoring
            monitoring:
              incidents:
                enabled: true
              perses:
                enabled: true
      when: monitoring_uiplugin.resources | selectattr('metadata.name', 'search', 'monitoring') | length == 0
  when: enable_perses_dashboard
