## ocp_hostpath vars
hostpath_setup_dir: ~/setup-files/hostpath-setup
hostpath_node: worker-0
hostpath_storage_size: 10Gi
hostpath_pv_storage_path: "/mnt/data"
hostpath_pod_image: nginx
hostpath_pod_mountpath: /usr/share/nginx/html
hostpath_pod_name: hostpath-storage
