kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-pvc-file-system
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: demo-storageclass


