kind: Secret
apiVersion: v1
metadata:
  name:  demo-secret
  namespace: default
type: Opaque
stringData:
  management_address: "{{ management_address }}" # Array management addresses
  username: "{{ username }}"     # Array username
data:
  password: "{{ password }}" # base64 array password

