---
- name: OCP ClusterLogging
  hosts: bastion
  tasks:
  - name: Include the global-secret-update role
    include_role:
        name: global-secret-update
    when: elasticsearch_clf_cs != "" and clusterlogging_clf_cs != ""

  - name: Include the ocp-cluster-log-forwarding role
    include_role:
        name: ocp-cluster-log-forwarding
  

